def build(ctx):
    ctx(rule='mkconstants.py ${SRC} ${TGT}',
        features='local',
        source='constants/memory.consts', target='boot/memory_c.asm kernel/memory_c.h')

    ctx.recurse("boot")
    ctx.recurse("kernel")

    ctx(rule='mkkernelimg.py ${SRC} ${TGT}',
        features='local',
        source='boot/bootblock kernel/kernel', target='rv6.img')
